// Solver-derived level metadata, generated by `npm run validate:levels`
// (scripts/validateLevels.ts) from the solvability proofs. levelMeta.json is a
// build artifact — regenerate it after any level change; never edit by hand.
//
// The headline field is `minSwitches`: the minimal number of control hand-offs
// between the two players across any solution — the level's *interaction
// intensity*. Communication is the game's goal, so high values late in the
// campaign are intended. The UI shows this as a static property of the level
// (like difficulty), NEVER as a par value or a score to compare the players'
// own play against: minimizing interaction is explicitly not the game's aim
// (docs/generative_levels.md §2.4).

import metaJson from './levelMeta.json';

export interface LevelMeta {
  /** Minimal AP expenditure proven by the solver (worst-case blind draws). */
  optimalCost: number;
  /** initialAP + Σ unlockValues − optimalCost. Gate: never < 1. */
  apSlack: number;
  /** DifficultyModel score (generative_levels.md §4). */
  difficulty: number;
  /** Minimal player hand-offs over all solutions — interaction intensity. */
  minSwitches: number;
  /** False when the search hit its node budget: value is an upper bound. */
  minSwitchesExact: boolean;
  /** Shared Unlock pairs the optimal solution triggers. */
  coordinationSteps: number;
  /** Blind Scrap-Pool draws the optimal solution relies on. */
  drawSteps: number;
  /** True when the level cannot be solved without touching the DNA Matrix. */
  matrixRequired: boolean;
}

const LEVEL_META = metaJson as Record<string, LevelMeta>;

export function getLevelMeta(levelId: string): LevelMeta | undefined {
  return LEVEL_META[levelId];
}
