// Display names for the level-select screen (kept in sync with the JSONs'
// "name" fields; validate:levels is the source of truth for content).
export const LEVEL_NAMES: Record<string, string> = {
  level_01: 'Tutorial: Movement',
  level_02: 'Locked Door',
  level_03: 'Column Shift',
  level_04: 'Scrap Pool',
  level_05: 'Shared Routing',
  level_06: 'Insert Sequence',
  level_07: 'T-Junction Coordination',
  level_08: 'Red Herring',
  level_09: 'Forced Rotation',
  level_10: 'Tight Budget',
  level_11: 'Convergence',
  level_12: 'Leap of Faith',
  level_13: 'Critical Rotation',
  level_14: 'Low Reserves',
  level_15: 'Master Set Teaser',
  level_16: 'Airlock',
  level_17: 'Signal Chain',
  level_18: 'Ghost Step',
  level_19: 'Phased Rendezvous',
  level_20: 'Dead Column',
  level_21: 'Synapse Toggle',
  level_22: 'Clot',
  level_23: 'Second Thoughts',
  level_24: 'Crossed Wires',
  level_25: 'Thin Place',
  level_26: 'First Spark',
  level_27: 'Steady Hand',
  level_28: 'Muscle Memory',
  level_29: 'Second Sight',
  // Levels 30-39: the Generator's first batch (SPRINT_029 follow-up,
  // 2026-07-23) — solver + headless-replay + real-browser verified, not
  // hand-authored. See SPRINTS/SPRINT_029-...md's "Generator Batch 1" note.
  level_30: 'First Threshold',
  level_31: 'Cold Current',
  level_32: 'Controlled Burn',
  level_33: 'Spark and Circuit',
  level_34: 'Deep Reserves',
  level_35: 'Ember Glimpse',
  level_36: 'Compound Interest',
  level_37: 'Blue Resonance',
  level_38: 'Triple Threat',
  level_39: 'Everything At Once',
  // Levels 40-49: Generator v2 batch (SPRINT_029 follow-up #2, 2026-07-23) —
  // multi-ability chains (up to 2 required core abilities) + scaled
  // gridRadius, past Batch 1's single-ability D≈6.2 plateau.
  level_40: 'Twin Gates',
  level_41: 'Burning Circuit',
  level_42: 'Vaulted Passage',
  level_43: 'The Long Corridor',
  level_44: 'Full Spectrum',
  level_45: 'Ashen Threshold',
  level_46: 'Wide Reach',
  level_47: 'Reserve Circuit',
  level_48: 'Distant Echo',
  level_49: 'The Far Shore',
};

export const LEVEL_ORDER: string[] = [
  'level_01',
  'level_02',
  'level_03',
  'level_04',
  'level_05',
  'level_06',
  'level_07',
  'level_08',
  'level_09',
  'level_10',
  'level_11',
  'level_12',
  'level_13',
  'level_14',
  'level_15',
  'level_16',
  'level_17',
  'level_18',
  'level_19',
  'level_20',
  'level_21',
  'level_22',
  'level_23',
  'level_24',
  'level_25',
  'level_26',
  'level_27',
  'level_28',
  'level_29',
  'level_30',
  'level_31',
  'level_32',
  'level_33',
  'level_34',
  'level_35',
  'level_36',
  'level_37',
  'level_38',
  'level_39',
  'level_40',
  'level_41',
  'level_42',
  'level_43',
  'level_44',
  'level_45',
  'level_46',
  'level_47',
  'level_48',
  'level_49',
];
